### ISSUE TITLE
Multiple find error when building images

### ISSUE THREAD

**Issue by r0n1am** [mbarbero/contained-java#1]
May I know the tested environment? When I am building the images, I always got multiples "find: ‘!-name’: No such file or directory" when using:

`make all`

some log sample:

```
Cleaning up layer target/mbarbero/distroless/base/layer
find: ‘!-name’: No such file or directory
...
find: ‘!-name’: No such file or directory
```

**Comment by mbarbero** [comment]
macOS. Thanks for the heads up.
